//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public System.Guid ErrorId { get; set; }
        public string IP_Address { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Message { get; set; }
    }
}
